
package it.postel.bancarizzazioneGUI.spedizione.sda.soap.stampaLDV;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-10-18T14:53:24.803+02:00
 * Generated source version: 3.3.1
 */

@WebFault(name = "SDAServiceException", targetNamespace = "http://stampaLDV.soap.sda.spedizione.bancarizzazioneGUI.postel.it/")
public class SDAServiceException_Exception extends Exception {

	private static final long serialVersionUID = -6001203580582914960L;
	private it.postel.bancarizzazioneGUI.spedizione.sda.soap.stampaLDV.SDAServiceException sdaServiceException;

    public SDAServiceException_Exception() {
        super();
    }

    public SDAServiceException_Exception(String message) {
        super(message);
    }

    public SDAServiceException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SDAServiceException_Exception(String message, it.postel.bancarizzazioneGUI.spedizione.sda.soap.stampaLDV.SDAServiceException sdaServiceException) {
        super(message);
        this.sdaServiceException = sdaServiceException;
    }

    public SDAServiceException_Exception(String message, it.postel.bancarizzazioneGUI.spedizione.sda.soap.stampaLDV.SDAServiceException sdaServiceException, java.lang.Throwable cause) {
        super(message, cause);
        this.sdaServiceException = sdaServiceException;
    }

    public it.postel.bancarizzazioneGUI.spedizione.sda.soap.stampaLDV.SDAServiceException getFaultInfo() {
        return this.sdaServiceException;
    }
}
