package it.postel.bancarizzazioneGUI.spedizione.sda.soap.stampaLDV;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-11-27T10:03:30.267+01:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "SpedizioneActionService",
                  wsdlLocation = "classpath:wsdl/sda/SpedizioneActionService.wsdl",
                  targetNamespace = "http://soap.service.spedizionews.sda.it/")
public class SpedizioneActionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.service.spedizionews.sda.it/", "SpedizioneActionService");
    public final static QName SpedizioneActionPort0 = new QName("http://soap.service.spedizionews.sda.it/", "SpedizioneActionPort.0");
    public final static QName SpedizioneActionPort = new QName("http://soap.service.spedizionews.sda.it/", "SpedizioneActionPort");
    static {
        URL url = SpedizioneActionService.class.getClassLoader().getResource("wsdl/sda/SpedizioneActionService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SpedizioneActionService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/sda/SpedizioneActionService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SpedizioneActionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SpedizioneActionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpedizioneActionService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SpedizioneActionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SpedizioneActionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SpedizioneActionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SpedizioneActionDelegate
     */
    @WebEndpoint(name = "SpedizioneActionPort.0")
    public SpedizioneActionDelegate getSpedizioneActionPort0() {
        return super.getPort(SpedizioneActionPort0, SpedizioneActionDelegate.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpedizioneActionDelegate
     */
    @WebEndpoint(name = "SpedizioneActionPort.0")
    public SpedizioneActionDelegate getSpedizioneActionPort0(WebServiceFeature... features) {
        return super.getPort(SpedizioneActionPort0, SpedizioneActionDelegate.class, features);
    }


    /**
     *
     * @return
     *     returns SpedizioneActionDelegate
     */
    @WebEndpoint(name = "SpedizioneActionPort")
    public SpedizioneActionDelegate getSpedizioneActionPort() {
        return super.getPort(SpedizioneActionPort, SpedizioneActionDelegate.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpedizioneActionDelegate
     */
    @WebEndpoint(name = "SpedizioneActionPort")
    public SpedizioneActionDelegate getSpedizioneActionPort(WebServiceFeature... features) {
        return super.getPort(SpedizioneActionPort, SpedizioneActionDelegate.class, features);
    }

}
