package it.postel.bancarizzazioneGUI.spedizione.sda.soap.stampaLDV;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-10-18T14:53:24.819+02:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://soap.service.spedizionews.sda.it/", name = "SpedizioneActionDelegate")
@XmlSeeAlso({ObjectFactory.class})
public interface SpedizioneActionDelegate {

    @WebMethod
    @RequestWrapper(localName = "doIt", targetNamespace = "http://soap.service.spedizionews.sda.it/", className = "it.sda.spedizionews.service.soap.DoIt")
    @ResponseWrapper(localName = "doItResponse", targetNamespace = "http://soap.service.spedizionews.sda.it/", className = "it.sda.spedizionews.service.soap.DoItResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.postel.bancarizzazioneGUI.spedizione.sda.soap.stampaLDV.DoItResponse.Return doIt(
        @WebParam(name = "arg0", targetNamespace = "")
        it.postel.bancarizzazioneGUI.spedizione.sda.soap.stampaLDV.DoIt.Arg0 arg0
    ) throws SDAServiceException_Exception;
}
